# FIXME: this version is obsolete. Stick to the latest one.
version: "3.7"
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
# FIXME: use meaningful name when possible. "bulk" as db name is ugly.
      MYSQL_DATABASE: bulk
      MYSQL_USER: bulk
      MYSQL_PASSWORD: bulk
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/bulk
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - .m2:/root/.m2

networks:
  springapimysql-net:
